# stochastic student configuration

_target_: s2p.models.stochastic_mlp_encoder_model.StochasticMLPEncoderModel

task: ${task}

cfg:
  hidden_dim: 512
  hidden_layers: 1
  head_hidden_dim: 512
  head_hidden_layers: 1
  latent_dim: ${latent_dimension}
  device: ${device}
  freeze: False
  checkpoint: null
  observation_key: null
  sample_mean: false