# stochastic student configuration

_target_: s2p.tasks.dmcontrol_task.DMControlTask

cfg:
  task_name: ???

  training_data_path: ${data_dir}/tdmpc2/mt30-${task_name}-training.pt
  validation_data_path: ${data_dir}/tdmpc2/mt30-${task_name}-validation.pt
  seed: ${seed}
  horizon: 4
  fraction: 1.0
  overlap_ratio: 0.0
  load_device: ${device}
  batch_device: ${device}